### PR TITLE
Yingqiao He's Homework 1

### PR DESCRIPTION
**Pull request by Yingqiao1**
I followed the homework instructions. 
1. I forked the file from GitHub class page to my own GitHub account
2. Then I copied/cloned the file from my GitHub to the RStudio of my own computer
3. I edited the file to include my brief self-introduction, using for syntax forms (header, emphasis, list, image).
4. I saved and committed every step of my editing, and pushed the changes to GitHub.
5. I checked the result in GitHhub, and found the lines are not tidy. So according to the instructor's suggestion, I added a space between each syntax form and each line I want to separate. 

By doing this homework, I learned how to contribute to GitHub repositories, and write proper comments on each step, and write clean and tidy lines using different syntax. I'm looking forward to learning more about R!

### CODE REVIEW

**Comment by wanitchayap** [comment]
Evaluation HW-01
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |     x      |              |            |
| **Coding strategy**         |     x      |              |            |
| **Presentation**            |     x      |              |            |
| **Achievement, creativity** |           |       x       |            |
| **Ease of access**          |      x     |              |            |

Remarks:
For the first three topic, since they are related to r code, I cannot evaluate and thus give the excellent scale. For the Achievement, creativity topic, I think you did a good job on completing the assignment as the instruction required. However, I think you could play a little bit more with Rmd (for example, trying links or other stuffs that might nor be required but will be useful in the future!). I can easily access your work, and I really like that you commit several times and describe each commit in details! That makes it easier for me to understand your working process. Nice picture by the way :)

**Comment by christinayu56** [comment]
Evaluation HW-01
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |     x      |              |            |
| **Coding strategy**         |     x      |              |            |
| **Presentation**            |    x       |              |            |
| **Achievement, creativity** |          |      x      |            |
| **Ease of access**          |    x       |              |            |

Remarks:

* Elaborate on above, especially for "needs work." Everything was great, I just would've loved some more creativity in the biography.
* Some specific praise? I thought your coding was simple, concise, and very easy to follow! 
* Something I learned? The ability to indent the list.
* Specific constructive criticism? Maybe branching out a bit more with markdown.
* Something I know and that you, my peer, might like to know because it is relevant to something you struggled with. I struggled a lot with inputing my image; committing the actual image to github helped alot.

**Review by bensoltoff — COMMENTED** [review]
Evaluation
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |     x      |              |            |
| **Coding strategy**         |    x       |              |            |
| **Presentation**            |       x    |              |            |
| **Achievement, creativity** |    x       |              |            |
| **Ease of access**          |    x       |              |            |

Remarks:

* Lots of Markdown elements, even a picture stored in the repo!
* [Take a look at this guide for which files in a repo should be committed and which can be ignored](https://cfss.uchicago.edu/hw00_homework_guidelines.html#which_files_to_commit)

**Comment by Yingqiao1** [comment]
Thank you very much for your valuable suggestions! I've learned a lot!

**Pull request closed without merging**
